### ISSUE TITLE
docker启动失败

### ISSUE THREAD

**Issue by liangxyz** [Nativu5/Gemini-FastAPI#13]
如题，使用portainer的stacks（就是docker-compose）部署无法启动，具体配置如下

![Image](https://github.com/user-attachments/assets/579e36a2-9ee3-4d96-be0d-0dd3014e273d)

错误日志：
2025-06-26 16:03:28.571 | ERROR    | app.utils.config:initialize_config:206 - Configuration validation failed: 1 validation error for Config
gemini
  Field required [type=missing, input_value={'server': {'host': '0.0....ng': {'level': 'DEBUG'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-26 16:03:30.018 | ERROR    | app.utils.config:initialize_config:206 - Configuration validation failed: 1 validation error for Config
gemini
  Field required [type=missing, input_value={'server': {'host': '0.0....ng': {'level': 'DEBUG'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-26 16:03:31.662 | ERROR    | app.utils.config:initialize_config:206 - Configuration validation failed: 1 validation error for Config
gemini
  Field required [type=missing, input_value={'server': {'host': '0.0....ng': {'level': 'DEBUG'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-26 16:03:33.079 | ERROR    | app.utils.config:initialize_config:206 - Configuration validation failed: 1 validation error for Config
gemini
  Field required [type=missing, input_value={'server': {'host': '0.0....ng': {'level': 'DEBUG'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing

**Comment by 3298636952** [comment]
+1

**Comment by wstanfeng** [comment]
+1

**Comment by wstanfeng** [comment]
一样的问题；

**Comment by Nativu5** [comment]
```
services:
  gemini-fastapi:
    image: ghcr.io/nativu5/gemini-fastapi:latest
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./cache:/app/.venv/lib/python3.12/site-packages/gemini_webapi/utils/temp
    environment:
      - CONFIG_SERVER__HOST=0.0.0.0
      - CONFIG_SERVER__PORT=8000
      - CONFIG_SERVER__API_KEY=${API_KEY}
      - CONFIG_GEMINI__CLIENTS__0__ID=client-a
      - CONFIG_GEMINI__CLIENTS__0__SECURE_1PSID=${SECURE_1PSID}
      - CONFIG_GEMINI__CLIENTS__0__SECURE_1PSIDTS=${SECURE_1PSIDTS}
    restart: on-failure:3 # Avoid retrying too many times
```
这个配置我这边是可以正常启动的，可以尝试手动 docker pull 一下 `ghcr.io/nativu5/gemini-fastapi:latest` 这个镜像，更新到最新版。另外注意 - ./config:/app/config 这个目录下面要放配置文件，如果这个配置文件有错误，也会报错。
